### ISSUE TITLE
Changing bonding rules

### ISSUE THREAD

**Issue by CorySimon** [patrickfuller/imolecule#28]
If I visualize a .xyz file, the bonds are inferred from distances between atoms. Is there a way I can modify the bonding rules?

i.e. change the cutoff distance between atom x and y beyond which a bond is declared to be present.

Some of the atoms that should be bonded are not.

**Comment by patrickfuller** [comment]
The file format converter is powered by openbabel, so that's where you want to look - particularly [OBMol.ConnectTheDots](http://openbabel.org/dev-api/classOpenBabel_1_1OBMol.shtml). To use open babel in the notebook with imolecule rendering, look at [cell 6 in the ipython notebook example](http://patrick-fuller.com/imolecule/examples/ipython.html).

**Comment by cortner** [comment]
I just stumbled over this issue: for what it's worth now, I found it *very straightforward*  to generate a JSON file in the format that `imolecule` reads.
